name: 'custom-action-template'

description: ''

branding:
  icon: database
  color: blue

inputs:
  node-working-directory:
    description: 'Node working directory'
    default: ''
  node-cache-key-suffix:
    description: 'Node cache key suffix'
    default: ''
  node-version:
    description: 'Node version'
    default: '20'
  go-version:
    description: 'Go version'
    default: '1.22.x'
  python-version:
    description: 'Python version'
    default: '3.11.x'
  pkl-version:
    description: 'PKL version'
    default: '0.25.3'

runs:
  using: composite
  steps:
    - name: Setup Golang
      uses: magnetikonline/action-golang-cache@main
      with:
        go-version: ${{ inputs.go-version }}

    - name: Setup NodeJS with cache
      uses: Drafteame/node-cache-action@main
      with:
        node-version: ${{ inputs.node-version }}
        working-directory: ${{ inputs.node-working-directory }}
        cache-key-suffix: ${{ inputs.node-cache-key-suffix }}

    - name: Setup Python
      uses: actions/setup-python@main
      with:
        python-version: ${{ inputs.python-version }}

    - name: Stup PKL
      uses: Drafteame/setup-pkl-action@main
      with:
        version: ${{ inputs.pkl-version }}

