name: 'custom-action-template'

description: ''

branding:
  icon: database
  color: blue

inputs:
  node:
    description: 'Enable NodeJS'
    default: 'false'
  node-working-directory:
    description: 'Node working directory'
    default: ''
  node-cache-key-suffix:
    description: 'Node cache key suffix'
    default: ''
  node-version:
    description: 'Node version'
    default: '20'

  go:
    description: 'Enable Go'
    default: 'true'
  go-version:
    description: 'Go version'
    default: '1.22.x'

  python:
    description: 'Enable Python'
    default: 'false'
  python-version:
    description: 'Python version'
    default: '3.11.x'

  pkl:
    description: 'Enable PKL'
    default: 'false'
  pkl-version:
    description: 'PKL version'
    default: '0.25.3'

  gitcmd:
    description: 'Enable Git'
    default: 'false'
  
  curl:
    description: 'Enable Curl'
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup Golang
      if: ${{ inputs.go == 'true' }}
      uses: magnetikonline/action-golang-cache@main
      with:
        go-version: ${{ inputs.go-version }}

    - name: Setup NodeJS with cache
      if: ${{ inputs.node == 'true' }}
      uses: Drafteame/node-cache-action@main
      with:
        node-version: ${{ inputs.node-version }}
        working-directory: ${{ inputs.node-working-directory }}
        cache-key-suffix: ${{ inputs.node-cache-key-suffix }}

    - name: Setup Python
      if: ${{ inputs.python == 'true' }}
      uses: actions/setup-python@main
      with:
        python-version: ${{ inputs.python-version }}

    - name: Setup PKL
      if: ${{ inputs.pkl == 'true' }}
      uses: Drafteame/setup-pkl-action@main
      with:
        version: ${{ inputs.pkl-version }}

    - name: Setup Git
      if: ${{ inputs.gitcmd == 'true' }}
      shell: bash
      run: |
        if ! [ -x "$(command -v git)" ]; then
          sudo apt-get install git -y
        else
          echo "Git already installed..."
        fi
    
    - name: Install curl
      if: ${{ inputs.curl == 'true' }}
      shell: bash
      run: |
        if ! [ -x "$(command -v curl)" ]; then
          sudo apt-get install curl -y
        else
          echo "curl already installed..."
        fi  

